#--------------------------------------------------------------------------------------------
#  Copyright (c) Red Hat, Inc. All rights reserved.
#  Licensed under the MIT License. See LICENSE in the project root for license information.
#--------------------------------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: node-guestbook-app
  labels:
    app: node-guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: node-guestbook
    tier: frontend
  ports:
    - port: 80
      targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-guestbook-apk
  labels:
    app: node-guestbook
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: node-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/eclipse/che-nodejs10-ubi:nightly
        command: ['/bin/sh', '-c']
        args: ['cd /home && git clone https://github.com/che-samples/nodejs-mongodb-sample.git && cd nodejs-mongodb-sample/ && npm install && npm start']
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
